version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
     - "27017:27017"
  web:
    build: .
    ports:
     - "80:80"
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     